//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class departamento
    {
        public int id_departamento { get; set; }
        public string departamentos { get; set; }
        public string nombre { get; set; }
        public Nullable<int> id_empleados { get; set; }
    
        public virtual empleados empleados { get; set; }
    }
}
