//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class salimes
    {
        public int id_filtroentrames { get; set; }
        public string codigoempleado { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string telefono { get; set; }
        public string departamento { get; set; }
        public string cargo { get; set; }
        public string fechaingreso { get; set; }
        public Nullable<int> salario { get; set; }
        public string estatus { get; set; }
    }
}
