//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class vacaciones
    {
        public int id_vacaciones { get; set; }
        public string empleado { get; set; }
        public string inicio_vacaciones { get; set; }
        public string Final_Vacaciones { get; set; }
        public string año_vacaciones { get; set; }
        public string comentario { get; set; }
        public Nullable<int> id_empleados { get; set; }
    
        public virtual empleados empleados { get; set; }
    }
}
